### ISSUE TITLE
can we have a slightly larger model?

### ISSUE THREAD

**Issue by dataf3l** [pbelcak/UltraFastBERT#10]
the currently published model is making errors, I wonder if a larger bert would probably fix the issue? 128 is too small.

**Comment by pbelcak** [comment]
The currently published model is designed for maximum FFF depth and performs (as described in the preprint), apart from the CoLA task, on par with GLUE baselines. It has max depth of 11 and uses only one FFF tree -- it is not clear what `128` you're referring to.

**Comment by dataf3l** [comment]
the BERT-UNCASED is a relatively smaller model, BERT seems to have a 128 token size window, so I figured it would be nice to have a BERT (LARGE?) model with perhaps a 512 window if such a thing even exists. @pbelcak I know it's designed for maximum depth but having other models would be awesome. the 128 refers to the context length

**Comment by pbelcak** [comment]
Yeah, following crammedBERT, we do not pretrain with longer sequences. But, with all code being public now, we do not bar any initiative in that direction.
