### ISSUE TITLE
How can I use your code?

### ISSUE THREAD

**Issue by superFilicos** [pbelcak/UltraFastBERT#15]
Dear author,
         Hi, I just read your paper and it's awesome. I'm wandering that among all these versions which one is best suitable for using in our transformer model. Of course I want to use GPU for training. Can I just use the fff_cuda to complete the whole training process like the normal feed forward layer？ and I also want to know did you try using fff_cuda on windows system? Thank you!

**Comment by pbelcak** [comment]
Hiya,

I'd rather wait for a while; we're currently working on an implementation of both forward and backward passes in Triton, which will deliver significant speedups on NVIDIA GPUs. Hopefully we'll be able to push something upstream by the end of the week.

**Comment by superFilicos** [comment]
Hi! 
         Thanks for your reply. But you did the whole training process with a single A6000 GPU like you said in your paper, I just want to do the same thing with you~ So how did you do that？Thank you!

**Comment by pbelcak** [comment]
That's actually something in which we followed the work on BERT "cramming" completely -- you can find more details in [this paper](https://arxiv.org/abs/2212.14034).
